name: dart_dashboard_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  objectbox: ^4.2.0
  ffi: ^2.1.4
  uuid: ^4.5.1
  alfred: ^1.1.2+1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  objectbox_generator: ^4.2.0
  test: ^1.24.0
